language: php

php:
  - 5.6

env:
  global:
    - MONGO_DB_NAME="vegas_test_media"
    - VEGAS_CMF_MEDIA_MONGO_PORT_27017_TCP_ADDR="localhost"
    - VEGAS_CMF_MEDIA_MONGO_PORT_27017_TCP_PORT=27017
    - VEGAS_CMF_MEDIA_MYSQL_PORT_3306_TCP_ADDR="localhost"
    - VEGAS_CMF_MEDIA_MYSQL_PORT_3306_TCP_PORT=3306
    - VEGAS_CMF_MEDIA_MYSQL_ENV_MYSQL_DATABASE="vegas_test_media"
    - VEGAS_CMF_MEDIA_MYSQL_ENV_MYSQL_USER="root"
    - VEGAS_CMF_MEDIA_MYSQL_ENV_MYSQL_PASSWORD
  matrix:
    - PHALCON_VERSION="3.0.x"
    - PHALCON_VERSION="v3.0.3"
    - PHALCON_VERSION="v3.0.2"
    - PHALCON_VERSION="v3.0.1"
    - PHALCON_VERSION="v3.0.0"

services:
  - mongodb
  - memcached

before_install:
  - printf "\n" | pecl install mongo &> /dev/null
  - printf "\n" | pecl install imagick &> /dev/null
  - mysql -e "CREATE DATABASE IF NOT EXISTS ${VEGAS_CMF_MEDIA_MYSQL_ENV_MYSQL_DATABASE};" -u${VEGAS_CMF_MEDIA_MYSQL_ENV_MYSQL_USER}

before_script:
  - ./travis/install-phalcon-extension.sh ${PHALCON_VERSION}
  - php --ri phalcon
  - travis_retry composer install --dev --no-interaction

script:
  - mkdir -p tests/fixtures/cache
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c travis/phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls -v